version: 0.2
run-as: root
phases:
  install:
    commands:
      - mkdir terraform
      - cd terraform
      - wget https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
      - unzip terraform_0.10.4_linux_amd64.zip
      - Sudo yum install unzip
      - unzip terraform_0.11.14_linux_amd64.zip
      - export PATH=$PATH:$HOME/terraform
      - terraform
      - cd vpc
  build:
      commands:
       - terraform init
       - terraform plan
       - terraform apply -auto-approve
      
