version: 0.2
run-as: root
env:
 parameter-store:
  AWS_ACCESS_KEY_ID_PARAM: /CodeBuild/AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY_PARAM: /CodeBuild/AWS_SECRET_ACCESS_KEY
phases:
  install:
    run-as: root
    commands:
    - pip install --upgrade pip
    - pip install awscli
    - aws configure set aws_access_key_id$AWS_ACCESS_KEY_ID_PARAM
    - aws configure set aws_secret_access_key$AWS_SECRET_ACCESS_KEY_PARAM
    - cat /etc/fedora-release
    - # export release=RHEL
    - # export release=AmazonLinux
    - export release=fedora
    - sudo dnf install -y dnf-plugins-core
    - sudo dnf config-manager --add-repo https://rpm.release.hashicorp.com/$release/hashicorp.repo
    - sudo dnf install -v terraform
    - terraform -help
  build:
   run-as: root
   commands:
    - terraform init
    - terraform apply 
    - terraform destroy
artifacts:
  files:
    - '**/*'
