version: 0.2
run-as: root
phases:
  install:
    commands:
      - curl -s -qL -o terraform_install.zip https://releases.hshicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin
      - chmod +x /usr/bin/terraform
     finally:
      - terraform --version
  build:
      commands:
        - cd vpc
        - pwd
       - terraform init
       - terraform apply -auto-approve
      
