version: 0.2
run-as: root
phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/0.13.1/terraform_0.13.1_linux_amd64.zip
      - unzip ./terraform_0.13.1_linux_amd64.zip 
      - echo $PATH
      - cp terraform /usr/local/sbin
      - terraform version
      - cd vpc
      
  build:
      commands:
       - terraform init
       - terraform apply -auto-approve
      
