version: 0.2
run-as: root
phases:
  install:
    commands:
      - sudo apt-get update -y
      - sudo apt-get install wget unzip -y
      - sudo wget https://releases.hashicorp.com/terraform/0.12.1.8/terraform_0.12.18_linux_amd64.zip
      - sudo unzip terraform_0.12.18_linux_amd64.zip
      - sudo install terraform /usr/local/bin/
      - terraform -version
  build:
      commands:
        - cd vpc
        - pwd
       - terraform init
       - terraform apply -auto-approve
      
