version: 0.2
run-as: root
phases:
  install:
    commands:
      - su -
      - apt -get install sudo -y
      - sudo yum install wget unzip
      - sudo wget https://release.hashicorp.com/terraform/0.12.2/terraform_0.12.2_linux_amd64.zip
      - sudo unzip ./terraform_0.12.2_linux_amd64.zip -d/usr/local/bin
      - terraform -v
      
  build:
      commands:
       - terraform init
       - terraform apply -auto-approve
      
