version: 0.2
run-as: root
phases:
  install:
    run-as: root
    commands:
     - sudo pip install boto3
     - wget https://releases.hashicorp.com/terraform/0.10.4/terraform_0.10.4_linux_amd64.zip
     - unzip terraform_0.10.4_linux_amd64.zip
     - sudo mv terraform /bin
     - rm terraform_0.10.4_linux_amd64.zip
     - sudo apt update
     - sudo apt-get install build-essential
     - sudo apt install git -y
     - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
     - eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
     - brew doctor
     - brew install gcc
     - brew tap hashicorp/tap
     - brew install terraform
     - terraform -help
     - terraform init
  build:
   run-as: root
   commands:
    - terraform init
    - terraform apply 
    - terraform destroy
artifacts:
  files:
    - '**/*'
