version: 0.2
run-as: root
phases:
  install:
    commands:
     - sudo pip install boto3
     - wget https://releases.hashicorp.com/terraform/0.10.4/terraform_0.10.4_linux_amd64.zip
     - unzip terraform_0.10.4_linux_amd64.zip
     - sudo mv terraform /bin
     - rm terraform_0.10.4_linux_amd64.zip
     - terraform init
  build:
   run-as: root
   commands:
    - terraform init
    - terraform apply -auto-approve 
    - terraform destroy -auto-approve
artifacts:
  files:
    - '**/*'
