version: 0.2
run-as: root
phases:
  install:
    commands:
      - mkdir ~/bin
      - wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
      - unzip terraform_0.12.24_linux_amd64.zip
      - mv terraform ~/bin
      - terraform version
  build:
    commands:
      - cd vpc
      - terraform init
      - terraform apply -auto-approve
      
