version: 0.2
run-as: root
phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install boto3
      - wget https://releases.hashicorp.com/terraform/0.10.4/terraform_0.10.4_linux_amd64.zip
      - unzip terraform_0.10.4_linux_amd64.zip
      - mv terraform /bin
      - cd vpc
  build:
      commands:
       - terraform init
       - terraform plan
       - terraform apply -auto-approve
      
