version: 0.2
run-as: root
phases:
  install:
    run-as: root
    runtime-versions:
      python: 3.x
    commands:
     - pip install --upgrade pip
     - pip install boto3
     - wget https://releases.hashicorp.com/terraform/0.10.4/terraform_0.10.4_linux_amd64.zip
     - unzip terraform_0.10.4_linux_amd64.zip
     - mv terraform /bin
     - cd vpc
     
  build:
   run-as: root
   commands:
    - terraform init -input=false
    -  terraform apply -auto-approve
artifacts:
  files:
    - '**/*'
