version: 0.2
run-as: root
phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
      - unzip terraform_0.12.24_linux_amd64.zip
      - mv terraform /usr/bin
      - which terraform
  build:
    commands:
      - cd vpc
      - terraform init
      - terraform apply -auto-approve
  post_build:
    commands:
      - terraform destroy -auto-approve
      
